ARG JAVA_BASE=11-jdk-openj9
FROM adoptopenjdk:${JAVA_BASE}
ENV JAVA_VERSION=${JAVA_BASE}

RUN groupadd spring && useradd --create-home --shell  /bin/bash --gid spring spring
USER spring:spring

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
COPY ./docker-entrypoint.sh /

RUN sh -c 'chmod +x /docker-entrypoint.sh'
RUN apt-get update && apt-get install -y haveged netcat curl jq

ENTRYPOINT "/docker-entrypoint.sh"

HEALTHCHECK --start-period=60s --interval=5s --timeout=20s --retries=3 \
   CMD curl --silent --request GET http://127.0.0.1:8080/actuator/health \
                   | jq --exit-status '.status == "UP"' || exit 1
