FROM kio.ee/base/go:1.18.4 as healthcheckBuild
WORKDIR /go/src/app

COPY cmd/healthcheck.go cmd/healthcheck.go

RUN  GO111MODULE=off CGO_ENABLED=0 go install ./...

# Set ownership and permissions as required
# 65532 - is appuser @runner.
RUN mkdir /app && chown -R 65532:65532 /app

FROM kio.ee/base/go:1.18.4 as entrypointBuild
WORKDIR /go/src/app
COPY cmd/entrypoint.go cmd/entrypoint.go

RUN  GO111MODULE=off CGO_ENABLED=0 go install ./...

FROM kkio.ee/base/java:17-jdk as builder

COPY target/example-app.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract

FROM kio.ee/base/java:17-jdk as runner

WORKDIR /app

COPY --from=builder  dependencies/ ./
COPY --from=builder snapshot-dependencies/ ./

# see https://github.com/moby/moby/issues/37965
LABEL maintainer="Aleksandr Muravja <alex@kyberorg.io>"

COPY --from=builder spring-boot-loader/ ./
COPY --from=builder application/ ./

COPY --from=healthcheckBuild /go/bin/cmd /app/healthcheck
COPY --from=entrypointBuild /go/bin/cmd /app/entrypoint
HEALTHCHECK --start-period=60s --interval=5s --timeout=20s --retries=3 CMD ["/app/healthcheck"]

# 65532 - is appuser @runner.
USER appuser

ENTRYPOINT ["/app/entrypoint"]
