version: '3'

networks:
  net:

services:
  app:
    build: ../..
    environment:
      SPRING_PROFILES_ACTIVE: local, actuator
      REDIS_HOST: redis
      REDIS_DB: 0
      REDIS_PASSWORD: redis-password
    ports:
      - "8080:8080"
    networks:
      - net
  # Database
  db:
    image: library/postgres:14.4-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_salaSana
    networks:
      - net
  # PG Admin4
  pga:
    depends_on:
      - db
    image: dpage/pgadmin4:6.12
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: yalsee@yals.ee
      PGADMIN_DEFAULT_PASSWORD: AXtYcRuhGZCkZVv4xLpgjpLVd
    networks:
      - net
  # Redis
  redis:
    image: library/redis:7.0.2
    command: [ "redis-server","--requirepass", "redis-password" ]
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    environment:
      MASTER: true
      REDIS_AUTH: redis-password
    networks:
      - net
  # Redis Commander
  redcom:
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - ./redis.connections.json:/redis-commander/config/local-production.json:ro
    environment:
        - REDIS_HOSTS=redis
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=redis-password
        - VIEW_JSON_DEFAULT=all
    networks:
      - net
