version: '3'

networks:
  net:

services:
  app:
    build: ../
    environment:
      SPRING_BOOT_PROFILES: local, actuator
    ports:
      - "8080:8080"
  # Database
  db:
    image: library/mariadb:10.5.9
    volumes:
      # Adjust me (app _db - is folder on host)
      - ./app_db:/var/lib/mysql
      - ./my.cnf:/etc/alternatives/my.cnf
    restart: always
    ports:
      - "3306:3306"
    environment:
      PMA_USER: user
      PMA_PASSWORD: pass
      MYSQL_DATABASE: example-app
      MYSQL_USER: example-user
      MYSQL_PASSWORD: example-password
      MYSQL_ROOT_PASSWORD: rootPassword
    networks:
      - net
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: library/phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootPassword
    networks:
      - net
