name: "Ship and Test - Dev"

on:
  push:
    branches-ignore:
      - trunk

jobs:
  ship2dev:
    name: Ship::Dev
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to kio.ee
        run: echo "${{ secrets.KIO_TOKEN }}" | docker login -u "${{ secrets.KIO_USER }}" --password-stdin kio.ee

      - name: Resolve Dependencies
        run: mvn --batch-mode --update-snapshots dependency:tree

      - name: Compile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production,noTesting

      - name: Docker build and tag
        run: docker build -f Dockerfile.DEV -t kio.ee/kyberorg/example-app:edge .

      - name: Docker push
        run: docker push kio.ee/kyberorg/example-app:edge

      - name: Get Docker image SHA256
        id: docker_image_sha
        run: echo "::set-output name=imageSha::$(docker images --digests | awk 'NR==2 {print $3}')"

      - name: Delete pushed image to prevent mess
        run: docker rmi kio.ee/kyberorg/example-app:edge
        continue-on-error: true

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEV_DEPLOY_HOOK }}?tag=edge@${{ steps.docker_image_sha.outputs.imageSha }}

      - name: Get deployed commit SHA
        id: deployed_commit
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Wait for site appears online
        uses: kyberorg/wait_for_new_version@v3
        with:
          url: https://dev-example.kyberorg.io
          responseCode: 200
          timeout: 120
          interval: 1.5
          hasActuator: true
          commitSha: ${{ steps.deployed_commit.outputs.sha }}

      - name: Test App
        continue-on-error: true
        run: mvn -Dtest.url=https://dev-example.kyberorg.io -Dgrid.hostname=http://grid.kio.ee -Dselenide.browser=chrome -Dtest.buildName=example-${{ github.run_id }} -Dsurefire.rerunFailingTestsCount=2 clean test

      - name: Publish Screenshots of failing tests, if any
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: failedTests
          path: target/reports/**/*.png
          if-no-files-found: ignore

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Dev Unit Test Results
          comment_title: Dev Unit Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          test_changes_limit: 5
          files: target/surefire-reports/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
          check_run_annotations: all tests, skipped tests
